@echo off

"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "10 Talismans.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "5 Spots II.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "5 Spots.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "7 Wonders.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "A Series of Unfortunate Events.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Abundante!.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Adventure Inlay Safari Edition.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Adventure Inlay.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Age of Japan.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Alchemy.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Ancient Sudoku.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Angkor.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Aqua Pearls.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Aquabble Quest.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Arctic Quest.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Atlantis Quest.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Atlantis.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Atomica Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Avalanche.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bang On Blitz.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Barnyard Invasion.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bejeweled 2 Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bengal - Game of Gods.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "BeTrapped!.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bewitched.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Big Kahuna Reef 2 - Chain Reaction.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Big Money.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Birds On A Wire.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bistro Stars.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bloxxit.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bounce Out Blitz.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Brickshooter Egypt.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bubblefish Bob.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bugged Out.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bunny Bounce Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Burger Rush.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bursting Bubbles.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Buzzy Bumble.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Cake Mania.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Cannon Blast!.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Captain BubbleBeard's Treasure.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Caveman Rock.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Chainz 2 - Relinked.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Chainz.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Chameleon Gems.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Charm Tale.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Chicken Invaders 2.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Chips.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Chuzzle Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Collapse! Crunch.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Color Harmony.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Combo Chaos.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Congo Cube.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Cosmic Stacker.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Crime Puzzle.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Crystal Path.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Crystalix.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Cubis Gold 2.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Cubis Gold.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Cycles.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Da Vinci's Secret.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Delicious Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Diamond Dash.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Diamond Detective.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Diamond Drop.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Diamond Mine.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Digby's Donuts.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Diner Dash 2 - Restaurant Rescue.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Diner Dash 3 - Flo on the Go.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Diner Dash.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Dropheads.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Dynomite.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Electric.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Equilibria.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "eTaco.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Fairies.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Family Feud 2.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Family Feud.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Fiber Twig 2.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Fiber Twig.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Fireworks Extravaganza.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Fitznik.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Flip or Flop.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Flower Quest.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Flower Shop - Big City Break.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Fortune Tiles Gold.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Fresco Wizard.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Fruit Lockers.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Fruit Smash.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Full Circle.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "GameHouse Sudoku.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Gearz.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Gem Shop.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Glow Worm.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Glyph.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Go Bingo.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Gold Fever.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Gold Rush.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Golden Sub.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Gravity Gems.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Gravity.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Hide and Secret.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "High Roller.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Holiday Express.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Huntsville - Mystery Case Files.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "I SPY Fantasy.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "I SPY Spooky Mansion Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "I SPY Treasure Hunt.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Ice Breaker.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Inca Quest.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Incadia.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Inspector Parker.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Inspheration.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "JEOPARDY!.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Jewel Match.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Jewel Miner.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Jewel of Atlantis.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Jewel Quest.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Jewels of Cleopatra.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Jurassic Realm.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Karu.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "King Kong - Skull Island Adventure.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Legend of Aladdin.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "LEGO Chic Boutique.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Lifetime RSVP.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Loco.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Lost City of Gold.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Lotus Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Luck Charm Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "LucyQ Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Luxor - Amun Rising.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Luxor 2.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Luxor Bundle Pack.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Luxor.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Mad Caps.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Magic Inlay.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Magic Match.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Magic Vines.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Mah-Jomino.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Maui Wowee.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Memory Loops.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Mind Machine.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Mirror Magic.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Mosaic - Tomb of Mystery.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Mummy Maze Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Mysteries of Horus.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Mystery Case Files - Prime Suspects.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Mysteryville.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Mystic Inn.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Noah's Ark Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Ocean Express.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Ouba - The Great Journey.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Pantheon.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Paparazzi.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Pat Sajak's Trivia Gems.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Penguin Puzzle.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Pharaoh's Arrows.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Phlinx to Go.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Picture Pyramid.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Pipsoh!.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Pirate Poppers.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Pixelus Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Pizza Frenzy.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Plantasia.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Poker Pop.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Poppit! To Go.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Power Chips.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Puzz Loop.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Puzzle Blast.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Puzzle Express.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Puzzle Inlay.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Puzzle Myth.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Puzzle Station.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "QBeez 2.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Qbeez.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Rain Drops.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Rainbow Mystery.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Rainbow Web.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Realms of Gold.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Rock & Roll JEOPARDY!.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Rocket Mania.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Roller Rush.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Rumble Cube.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Runic One.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Scarabs of Pharaoh.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Shape Shifter.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Shapo Gold.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Shopmania.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Sky Bubbles Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Slingo Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Slingo Quest.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Slyder Adventures.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Snowy - Puzzle Islands.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Spacebound.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Sparkle.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "SpongeBob SquarePants Collapse!.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Spring Sprang Sprung.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "SquareOff Gold.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Stand O' Food.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Stones of Khufu.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Sudoku - Latin Squares Gold.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Sudoku Maya Gold.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Sudoku Quest.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super Bounce Out.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super Candy Cruncher.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super Collapse 2 Platinum.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super Collapse 2.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super Collapse 3.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super Collapse! Puzzle Gallery.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super Collapse.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super Gem Drop.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super Glinx.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super Groovy.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super Nisqually.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super PileUp!.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super Pop and Drop.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Sveerz.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Talismania Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Teddy Factory.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "The Da Vinci Code.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "The Legend of El Dorado.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "The Sudoku Challenge.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Tiki Boom Boom.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Tip Top.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Treasure Fall.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Treasure Island.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Treasures of Montezuma.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Trick or Treat Smash.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Triclops.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "TriJinx.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Trivia Machine.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Tropical Swaps.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Tropix.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Tumblebugs.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Twist Lingo.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Twisty Tracks.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Walls of Jericho.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Wild West Wendy.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Wobbly Bobbly.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Wonderlines.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Xango Tango.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Zodiac Tower.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Zulu Gems.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Zuma Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Zzed.iss"

rem NEW GAMES ADDED

"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Little Shop of Treasures.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Mariposa.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Jewel Quest II.iss"

cls
echo Puzzle Scripts Compiling Complete!
pause>nul
exit