@echo off

"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Academy of Magic - Word Spells.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Acropolis.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Babel Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Big Kahuna Words.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Boggle Supreme.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bonnie's Bookstore.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bookworm Adventures.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bookworm Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Chicktionary.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Dungeon Scroll.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Flip Words.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "GameHouse Word Collection.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Great Wall of Words.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Greedy Words.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Icy Spell.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Infinite Crosswords.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Jig Words.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Pat Sajak's Lucky Letters.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Puzzle Word.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Reader's Digest Super Word Power.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "SandScript.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Scrabble - GameHouse Edition.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Scrabble Blast!.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Scrabble Rack Attack.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Scrabble.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Shangri La Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Slot Words.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Spell Bound.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Spellagories.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Spellunker.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Spelvin.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Spider-Man 2 Web of Words.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super TextTwist.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super WHATword.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super Wild Wild Words.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Text Express.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Thomas and the Magical Words.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Typer Shark Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "USA Today - Infinite Crosswords.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Weave Words.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Wheel of Fortune.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Word Buzz Gold.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Word Challenger.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Word Craft.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Word Cross.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Word Harmony.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Word Island.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Word Jolt.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Word Mojo Gold.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Word Monaco.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Word Search Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Word Slinger.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Word Spiral.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Word Travels.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Word Wizard.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Word Zen - Mahjongg Reinvented.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "WordJong To Go.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "WordUp.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Writer's Block.iss"

cls
echo Word Scripts Compiling Complete!
pause>nul
exit