@echo off

"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Action Ball Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Adventure Ball.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Aironix.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Alien Sky.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "AquaPark.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Astrobatics.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "AstroPop Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Atari Arcade Hits.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Atomaders.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Atomic Pongling.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Aztec Ball.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Ballistik.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Balls of Steel - Creature Attack!.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bliss Island.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "BreakQuest.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bricks of Atlantis.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bricks of Camelot.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bricks of Egypt 2.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bricks of Egypt.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bugatron Worlds.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Bugix.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Cactus Bruce and the Corporate Monkeys.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Caramba Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Chicken Attack.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Chicken Rush.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Cosmic Bugs.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Devil's Island Pinball.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Fairy Treasure.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "FizzBall.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Flyonoid.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "FreakOut Gold.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Froggy Castle 2.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Froggy Castle.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Funkiball Adventure.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Gold Miner Special Edition.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Gold Miner Vegas.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Hammer Heads Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Hamsterball.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Heavy Weapon Deluxe.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Hyperballoid - The Next Challenge.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Hyperballoid.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Impact.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Incredible Ink.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Invadazoid.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Magic Ball 2 - New Worlds.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Magic Ball 2.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Marble Blast Gold.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "NeoBall.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Orbz.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Platypus II.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Platypus.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Rebound Lost Worlds - Recharged.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Rebound Lost Worlds.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Rebound.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Rocks N' Rockets.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Runic.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Shattera.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Snowball Run.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Snowy - Space Trip.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Snowy - The Bear's Adventures.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Snowy - Treasure Hunter 2.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Snowy - Treasure Hunter.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Spin & Win.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Splash.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Sportball Challenge.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Star Defender 2.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Strike Ball 2.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Super Tap-a-Jam.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Tamale Loco - Rumble in the Desert II.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Temple of Bricks.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Time Breaker.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "UltraBall.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Varmintz.iss"
"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Water Bugs.iss"

rem NEW GAMES

"C:\Program Files\Inno Setup 5\Compil32.exe" /cc "Peggle Deluxe.iss"

cls
echo Arcade Scripts Compiling Complete!
pause>nul
exit